from beanie import Document, PydanticObjectId
from pydantic import Field
from typing import Optional, List
from datetime import datetime


class Look(Document):
    user_id: PydanticObjectId
    anchor_item_id: PydanticObjectId          # the item that triggered the styling session
    item_ids: List[PydanticObjectId] = []     # all wardrobe items in this look (including anchor)
    name: str = ""                            # auto-generated by Claude e.g. "Rooftop dinner, NYC"
    occasion: str = ""
    season: List[str] = []
    source: str = "styled"                    # "styled" | "trip" | "daily"
    source_trip_id: Optional[PydanticObjectId] = None
    avatar_image_url: Optional[str] = None    # fal.ai generated avatar wearing this look
    styling_notes: str = ""                   # Claude's full styling rationale
    claude_outfit_description: str = ""       # what Claude told fal.ai exactly
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Settings:
        name = "looks"
